SELECT COUNT(DISTINCT CIH.INVOICE_NUMBER) AS unique_invoice_numbers,
       COUNT(*) AS total_invoices,
       --CIH.PAYMENT_DATE,
       --CRB.RATE,
       SUM(CIH.AMOUNT_DUE * CRB.RATE) AS amount_due_usd
       --CCB.NAME AS currency_name
FROM COUPA_INVOICE_HEADER_BCV CIH
LEFT JOIN COUPA_INVOICE_LINE_BCV CIL
    ON CIL.INVOICE_HEADER_ID = CIH.ID
LEFT JOIN COUPA_EXCHANGE_RATE_BCV CRB
    ON CIL.CURRENCY_ID = CRB.TO_CURRENCY_ID
--LEFT JOIN COUPA_CURRENCY_BCV CCB
--    ON CRB.CURRENCY_CODE = CCB.CODE
WHERE CIH.PAYMENT_DATE > '2025-11-15'
AND CRB.FROM_CURRENCY_ID = 1;

--IS CORRECT?

--SHOULD I RATHER SUM IN A FOLLOWING CTE AND UNCOMMENT 
