CREATE OR REPLACE TABLE _SANDBOX_WORKING_CAPITAL.WORKING_CAPITAL.WC_AP_ZDP AS
SELECT *
FROM _SANDBOX_WORKING_CAPITAL.WORKING_CAPITAL.WC_AP_ZDP_BKP
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY INVOICE__, SUPPLIER, PAYMENT_DATE, REQUESTER, TOTAL_USD, INVOICE_DATE
  ORDER BY CREATED_DATE DESC, INVOICE_RECEIVED_DATE DESC, NET_DUE_DATE DESC
) = 1;

--- Before we had $34.95M, now we have $29.9 for May
